export const DATA_KEY_TO_LABEL: Record<string, string> = {
  "front-forearm-right": "Гарын шуу баруун",
  "front-hand-right": "Гар баруун",
  "front-upper-arm-right": "Гар дээд баруун",
  "front-elbow-right": "Тохой баруун",
  "front-thigh-right": "Хөл дээд баруун",
  "front-knee-right": "Өвдөг баруун",
  "front-shin-right": "Хөл доод баруун",
  "front-foot-right": "Хөл баруун",
  "front-thigh-left": "Хөл дээд зүүн",
  "front-knee-left": "Өвдөг зүүн",
  "front-shin-left": "Хөл доод зүүн",
  "front-foot-left": "Хөл зүүн",
  "front-head": "Толгой",
  "front-neck": "Хүзүү",
  "front-groin": "Гэдэс",
  "front-forearm-left": "Гарын шуу зүүн",
  "front-hand-left": "Гар зүүн",
  "front-upper-arm-left": "Гар дээд зүүн",
  "front-elbow-left": "Тохой зүүн",
  "front-abdomen": "Хэвлий",
  "front-chest-left": "Цээж зүүн",
  "front-chest-right": "Цээж баруун",
  "front-hip-left": "Хажуу зүүн",
  "front-hip-right": "Хажуу баруун",
  "back-knee-left": "Өвдөг зүүн",
  "back-calf-left": "Хөл доод зүүн",
  "back-foot-left": "Хөл зүүн",
  "back-head": "Толгой",
  "back-neck": "Хүзүү",
  "back-buttock-left": "Бөгс зүүн",
  "back-forearm-left": "Гарын шуу зүүн",
  "back-hand-left": "Гар зүүн",
  "back-upper-arm-left": "Гар дээд зүүн",
  "back-elbow-left": "Тохой зүүн",
  "back-forearm-right": "Гарын шуу баруун",
  "back-hand-right": "Гар баруун",
  "back-upper-arm-right": "Гар дээд баруун",
  "back-elbow-right": "Тохой баруун",
  "back-thigh-left": "Хөл дээд зүүн",
  "back-knee-right": "Өвдөг баруун",
  "back-calf-right": "Хөл доод баруун",
  "back-foot-right": "Хөл баруун",
  "back-buttock-right": "Бөгс баруун",
  "back-thigh-right": "Хөл дээд баруун",
  "back-shoulderblade-left": "Мөр зүүн",
  "back-loin-left": "Нуруу зүүн",
  "back-shoulderblade-right": "Мөр баруун",
  "back-loin-right": "Нуруу баруун",
};
